import { randomUUID } from 'node:crypto';
import { db } from './db.mjs';
import { cents, stages, followupTypes } from '../src/domain.js';
export const uid=()=>randomUUID();
export const now=()=>new Date().toISOString();
export const amount=value=>cents(value)/100;
export function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}(?:T\d{2}:\d{2}(?::\d{2}(?:\.\d+)?)?(?:Z|[+-]\d{2}:\d{2}))?$/.test(value)||!Number.isFinite(Date.parse(value)))throw new Error('Fecha inválida. Usa fecha y hora de Ecuador.');const day=value.slice(0,10),check=new Date(`${day}T12:00:00Z`);if(check.toISOString().slice(0,10)!==day)throw new Error('La fecha no existe.');return value.length===10?`${value}T12:00:00-05:00`:new Date(value).toISOString();}
export const audit=(id,before,after,actor)=>db.prepare('INSERT INTO lead_audit_log(id,lead_id,actor_id,operation,before_data,after_data) VALUES(?,?,?,?,?,?)').run(uid(),id,actor,before?'UPDATE':'INSERT',before?JSON.stringify(before):null,JSON.stringify(after));
export function activity(leadId,actor,type,subject,body=null){const timestamp=now();db.prepare('INSERT INTO activities(id,lead_id,created_by,type,subject,body,occurred_at,completed_at) VALUES(?,?,?,?,?,?,?,?)').run(uid(),leadId,actor,type,subject,body,timestamp,timestamp);db.prepare('UPDATE leads SET last_contact_at=?,updated_at=? WHERE id=?').run(timestamp,timestamp,leadId);const lead=db.prepare('SELECT * FROM leads WHERE id=?').get(leadId);const target={call:'contacted',whatsapp:'contacted',email:'contacted',meeting:'meeting_completed',proposal:'proposal_sent'}[type];if(target&&!lead.deleted_at&&!['won','lost'].includes(lead.status)&&stages.findIndex(x=>x[0]===target)>stages.findIndex(x=>x[0]===lead.status)){setStage(lead,target,actor);audit(leadId,lead,db.prepare('SELECT * FROM leads WHERE id=?').get(leadId),actor);}}
export function syncNext(leadId,actor){const lead=db.prepare('SELECT * FROM leads WHERE id=?').get(leadId);const next=db.prepare("SELECT * FROM followups WHERE lead_id=? AND status='pending' ORDER BY due_at,id LIMIT 1").get(leadId);const action=next?.description||null,due=next?.due_at||null;if(lead.next_action===action&&lead.next_action_at===due)return;db.prepare('UPDATE leads SET next_action=?,next_action_at=?,updated_at=?,updated_by=? WHERE id=?').run(action,due,now(),actor,leadId);}
export function createFollowup(lead,body,actor){if(lead.deleted_at||['won','lost'].includes(lead.status))throw new Error('Crea seguimientos solo en oportunidades activas.');const type=body.type||'other',description=String(body.description||'').trim();if(!followupTypes.some(x=>x[0]===type)||!description||description.length>1000)throw new Error('Indica tipo y descripción del seguimiento.');const id=uid();db.prepare('INSERT INTO followups(id,lead_id,owner_id,due_at,type,description,created_by) VALUES(?,?,?,?,?,?,?)').run(id,lead.id,lead.owner_id,validDate(body.due_at),type,description,actor);syncNext(lead.id,actor);const created=db.prepare('SELECT * FROM followups WHERE id=?').get(id);audit(lead.id,{followup_id:id,status:null},{...created,followup_id:id},actor);return created;}
export function saleFor(lead,total){const existing=db.prepare('SELECT * FROM sales WHERE lead_id=?').get(lead.id);if(existing){if(total!==undefined){const value=amount(total);if(!Number.isFinite(value)||!Number.isSafeInteger(cents(value))||value<=0||cents(value)<cents(existing.collected_amount))throw new Error('El valor final debe ser positivo y no menor a lo cobrado.');db.prepare('UPDATE sales SET total_value=?,pending_balance=?,updated_at=? WHERE id=?').run(value,amount(value-existing.collected_amount),now(),existing.id);}return existing.id;}
 const value=amount(total);if(!Number.isFinite(value)||!Number.isSafeInteger(cents(value))||value<=0)throw new Error('Indica el valor final acordado para marcar Ganado.');const id=uid(),rate=Number(db.prepare("SELECT value FROM settings WHERE key='commission_rate'").get().value);db.prepare('INSERT INTO sales(id,lead_id,total_value,pending_balance,signed_at) VALUES(?,?,?,?,?)').run(id,lead.id,value,value,now());db.prepare('INSERT INTO commissions(id,sale_id,owner_id,rate) VALUES(?,?,?,?)').run(uid(),id,lead.owner_id,rate);return id;
}
export function recomputeSale(saleId){const sale=db.prepare('SELECT * FROM sales WHERE id=?').get(saleId),commission=db.prepare('SELECT * FROM commissions WHERE sale_id=?').get(saleId);if(!sale||!commission)throw new Error('Venta sin comisión asociada. Revisa el registro.');const collected=db.prepare("SELECT COALESCE(SUM(ROUND(amount*100)),0) AS total FROM payments WHERE sale_id=? AND status='confirmed'").get(saleId).total;const generated=Math.round(collected*commission.rate);if(collected>cents(sale.total_value))throw new Error('El monto excede el saldo pendiente.');if(generated<cents(commission.paid_amount))throw new Error('Este cambio dejaría la comisión generada por debajo de lo ya pagado.');db.prepare('UPDATE sales SET collected_amount=?,pending_balance=?,updated_at=? WHERE id=?').run(collected/100,(cents(sale.total_value)-collected)/100,now(),saleId);db.prepare('UPDATE commissions SET generated_amount=?,status=?,updated_at=? WHERE id=?').run(generated/100,generated===cents(commission.paid_amount)&&generated>0?'paid':commission.paid_amount>0?'partial':'pending',now(),commission.id);}
export function setStage(lead,status,actor,finalValue,reason){if(!stages.some(s=>s[0]===status))throw new Error('Etapa no válida.');if(lead.deleted_at)throw new Error('Restaura la oportunidad antes de cambiar su estado.');if(status==='lost'&&!String(reason||lead.loss_reason||'').trim())throw new Error('Indica el motivo de pérdida.');if(status==='won')saleFor(lead,finalValue);else if(finalValue!==undefined)throw new Error('El valor final se registra al ganar la oportunidad.');if(status!==lead.status){db.prepare('INSERT INTO lead_status_history(id,lead_id,old_status,new_status,actor_id) VALUES(?,?,?,?,?)').run(uid(),lead.id,lead.status,status,actor);}
 if(['won','lost'].includes(status)){db.prepare("UPDATE followups SET status='cancelled',updated_at=? WHERE lead_id=? AND status='pending'").run(now(),lead.id);}
 db.prepare('UPDATE leads SET status=?,loss_reason=?,updated_by=?,updated_at=? WHERE id=?').run(status,status==='lost'?String(reason||lead.loss_reason):null,actor,now(),lead.id);
 syncNext(lead.id,actor);
}
export function financialSummary(user){const params=user.role==='admin'?[]:[user.id],where=user.role==='admin'?'':' WHERE l.owner_id=?';const rows=db.prepare(`SELECT s.*,l.status,COALESCE((SELECT SUM(ROUND(p.amount*100)) FROM payments p WHERE p.sale_id=s.id AND p.status='confirmed'),0)/100.0 AS confirmed_amount FROM sales s JOIN leads l ON l.id=s.lead_id${where}`).all(...params);let sold=0,collected=0,balance=0,won=0;for(const s of rows){if(s.status==='won'){sold+=cents(s.total_value);balance+=Math.max(0,cents(s.total_value)-cents(s.confirmed_amount));}collected+=cents(s.confirmed_amount);}
 won=db.prepare(`SELECT COUNT(*) AS count FROM leads WHERE status='won'${user.role==='admin'?'':' AND owner_id=?'}`).get(...params).count;
 const com=db.prepare(`SELECT c.*,ROUND(COALESCE((SELECT SUM(ROUND(p.amount*100)) FROM payments p WHERE p.sale_id=c.sale_id AND p.status='confirmed'),0)*c.rate)/100.0 AS real_generated FROM commissions c${user.role==='admin'?'':' WHERE c.owner_id=?'}`).all(...params);return {sold:sold/100,collected:collected/100,balance:balance/100,won,generated:com.reduce((n,c)=>n+cents(c.real_generated),0)/100,paid:com.reduce((n,c)=>n+cents(c.paid_amount),0)/100,pending:com.reduce((n,c)=>n+cents(c.real_generated)-cents(c.paid_amount),0)/100};}
